import type { SeedAlpha } from "../types";

/**
 * Seed Alpha Factory — mix of Kou et al. (Findings of EMNLP 2025) formulas
 * and WorldQuant-style LLM-looking expressions. Executable on OHLCV only.
 */
export const SEED_LIBRARY: SeedAlpha[] = [
  {
    id: "A01",
    name: "Price momentum 14",
    category: "momentum",
    expression: "close - delay(close, 14)",
    source: "paper",
    rationale: "CLOSE - DELAY(CLOSE, 14). Residual trend vs two-week lag.",
  },
  {
    id: "A02",
    name: "Volume momentum 14",
    category: "momentum",
    expression: "volume - delay(volume, 14)",
    source: "paper",
    rationale: "VOLUME - DELAY(VOLUME, 14). Participation persistence.",
  },
  {
    id: "A03",
    name: "RSI momentum",
    category: "momentum",
    expression: "rsi - delay(rsi, 14)",
    source: "paper",
    rationale: "RSI - DELAY(RSI, 14). Acceleration of Wilder RSI.",
  },
  {
    id: "A04",
    name: "Detrended price oscillator",
    category: "momentum",
    expression: "close - delay(sma(close, 14), 7)",
    source: "paper",
    rationale: "CLOSE - DELAY(SMA(CLOSE, 14), 7). Paper Fig. 4 seed.",
  },
  {
    id: "A05",
    name: "SMA reversion 20",
    category: "meanrev",
    expression: "sma(close, 20) - close",
    source: "paper",
    rationale: "MA(CLOSE, 20) - CLOSE. Distance below the 20-day mean.",
  },
  {
    id: "A06",
    name: "Z-score reversion",
    category: "meanrev",
    expression: "(close - sma(close, 20)) / std(close, 20)",
    source: "paper",
    rationale: "Z-score of close vs 20-day window. Fade stretched names.",
  },
  {
    id: "A07",
    name: "Distance from high",
    category: "meanrev",
    expression: "ts_max(high, 20) - close",
    source: "paper",
    rationale: "MAX(HIGH, 20) - CLOSE. Pullback from local peak.",
  },
  {
    id: "A08",
    name: "RSI reversion",
    category: "meanrev",
    expression: "100 - rsi",
    source: "paper",
    rationale: "(100 - RSI). Overbought/oversold inversion.",
  },
  {
    id: "A09",
    name: "Bollinger width",
    category: "volatility",
    expression: "(boll_up - boll_down) / sma(close, 20)",
    source: "paper",
    rationale: "(BOLL_UP - BOLL_DOWN) / SMA(CLOSE, 20). Band squeeze.",
  },
  {
    id: "A10",
    name: "Vol ratio 10/50",
    category: "volatility",
    expression: "std(close, 10) / std(close, 50)",
    source: "paper",
    rationale: "STD(CLOSE, 10) / STD(CLOSE, 50). Short vs long dispersion.",
  },
  {
    id: "A11",
    name: "ATR momentum",
    category: "volatility",
    expression: "atr - delay(atr, 14)",
    source: "paper",
    rationale: "ATR - DELAY(ATR, 14). Expanding true range.",
  },
  {
    id: "A12",
    name: "High-low spread",
    category: "liquidity",
    expression: "(high - low) / close",
    source: "paper",
    rationale: "(HIGH - LOW) / CLOSE. Intraday range as a liquidity proxy.",
  },
  {
    id: "A13",
    name: "Dollar volume",
    category: "liquidity",
    expression: "volume * close",
    source: "paper",
    rationale: "VOLUME * CLOSE. Capacity / trading activity.",
  },
  {
    id: "A14",
    name: "Amihud-like",
    category: "liquidity",
    expression: "abs(returns) / volume",
    source: "paper",
    rationale: "ABS(RETURN) / VOLUME. Price impact per unit volume.",
  },
  {
    id: "A15",
    name: "Volume ROC",
    category: "liquidity",
    expression: "(volume - delay(volume, 14)) / delay(volume, 14)",
    source: "paper",
    rationale: "VROC. Relative change in participation.",
  },
  {
    id: "A16",
    name: "Williams %R",
    category: "technical",
    expression: "((ts_max(high, 14) - close) / (ts_max(high, 14) - ts_min(low, 14))) * -100",
    source: "paper",
    rationale: "Williams %R. Close location in 14-day range.",
  },
  {
    id: "A17",
    name: "Stochastic oscillator",
    category: "technical",
    expression: "((close - ts_min(low, 14)) / (ts_max(high, 14) - ts_min(low, 14))) * 100",
    source: "paper",
    rationale: "Stochastic %K. Paper technical family.",
  },
  {
    id: "A18",
    name: "MACD level",
    category: "technical",
    expression: "macd",
    source: "paper",
    rationale: "EMA(12) - EMA(26). Trend-following oscillator.",
  },
  {
    id: "A19",
    name: "Delta vs volume rank",
    category: "momentum",
    expression: "rank(ts_delta(close, 5)) - rank(volume)",
    source: "llm",
    rationale: "LLM-style: 5-day price delta ranked against raw volume rank.",
  },
  {
    id: "A20",
    name: "Signed corr power",
    category: "quality",
    expression: "signedpower(rank(correlation(ts_delta(close, 1), ts_delta(volume, 1), 10)), 0.5)",
    source: "llm",
    rationale: "LLM-style: compress ranked price-volume correlation with signedpower.",
  },
  {
    id: "A21",
    name: "Close/open ts-rank spread",
    category: "quality",
    expression: "rank(ts_rank(close, 20) - ts_rank(open, 20))",
    source: "llm",
    rationale: "Intraday accumulation via ts_rank(close) vs ts_rank(open).",
  },
  {
    id: "A22",
    name: "Quiet volume + low vol",
    category: "quality",
    expression: "-rank(ts_std(returns, 20)) + rank(ts_mean(volume, 5) / ts_mean(volume, 20))",
    source: "llm",
    rationale: "Prefer rising near-term volume while realized vol is compressed.",
  },
  {
    id: "A23",
    name: "Ranked 5d residual",
    category: "momentum",
    expression: "rank((close - delay(close, 5)) / ts_std(close, 20)) - rank(high - low)",
    source: "wq",
    rationale: "Vol-scaled 5-day move minus range; classic WQ skeleton.",
  },
  {
    id: "A24",
    name: "Decay of rank(close)",
    category: "technical",
    expression: "ts_delta(rank(close), 3)",
    source: "wq",
    rationale: "Cross-sectional rank momentum over 3 sessions.",
  },
];

export const CATEGORY_LABEL: Record<SeedAlpha["category"], string> = {
  momentum: "MOM",
  meanrev: "MRV",
  volatility: "VOL",
  liquidity: "LIQ",
  technical: "TEC",
  quality: "QTY",
};

export const WC = 0.6;
export const WR = 0.4;
export const TAU = 0.58;
